language: objective-c
osx_image: xcode7.2
xcode_project: FormChangeable.xcodeproj
xcode_scheme: FormChangeable
xcode_sdk: iphonesimulator9.2
env:
  global:
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.2"
  - FRAMEWORK_NAME=FormChangeable
branches:
  only:
  - master
  - develop
  - "/^v?[0-9\\.]+/"
before_install:
- brew update
- brew unlink carthage
- brew install carthage
script:
- pod lib lint
- set -o pipefail
- xctool -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO | xcpretty -c
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME"
  -destination "$DESTINATION" | xcpretty -c
before_deploy:
- carthage build --no-skip-current
- carthage archive "$FRAMEWORK_NAME"
deploy:
  provider: releases
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: "$TRAVIS_REPO_SLUG"
    tags: true
  api-key:
    secure: b1vyf2jAj4JvEKGc1LIYfuGXkoceCib7hUNyp8DkMDBWqqv1G3gWjfkC3EuxR677eEg2ak/yBcIchDLxp4WeQxmDJXYWQxbNMJcmxTT54CLiWh8j0GoM2huQ0C9xaswY9VLrwU9lqxY7mkSl9TCs7YU1Q2E3g0tiKHP7PQCF+hPQo/d0DJY4DvhVK3E+dP1EGiS+1KiOTijHWnascNc0BP/pHRxTbVnmRSlY1yMpWN55zRvKHsPhCvoYpRXQu+nB6o83RSkmRFSvT0ARAqhnX6qZo3LwsxvHZ4g+2XZj/yr0QRXF3Fi9NmXQ+/5m9Tqy1/2d5mWwfhWpNaeAb1zlt7xPfzpqR0sek7JyJ9qs+MrmiipR3+Q8J7kkQIM580L+ZID3O+9++imjnl6ff+7PBfzt3puz4SYIGtASKMz3Peu6UYEhpfPVIwXo4oKrW649I9MzYnu6JudmLNDLGosc33aHWv+p9oUzlH5Nl7EiNzhL2I66HOEG5FeSJ6tkP7kSrd0MM58zrzNeY29ScgLD3PFxAkc6APMqWK+kBAdha3X0WiYZYBwrRonixEUTHbRmbw1LOMytc9Z6kvoQZBShuNLjTEYqZXAC+8u7l2qCZUe/C+ad3LXDgY7KSOieM0ln+d+H+cXsH8tkHZD4MgInGWg1yQg4QhflK8VEBa+eegY=
notifications:
  email: false
  slack:
    secure: g4xZWffoVbcScW7534/dlwm8OZ1diECOeJfWFRcLGzWDd6H0RtSKuk8ebFOLciNYDOjlf8H9+gktR1jis+jN1vv75SSKIhPqFJ2/B8srdha3EFEyFxzuIbCa2+1vbw/Y6z+Jb7+GGSzId+JVnoCsDlhxY8RLY23E5IJ1O2YCO4XSeothc1U5GNXlNhI6vKD6BSGD2oy15K6C1bAY0YkqSGVyGBBRbbczEjpeljHfw7BiGPfrTVJ65tCHzw9ZtIkevdA+LYSpcJ0EkF6i15xMViOzlxqr+s/6ABcf+9BYfpTlXQqLtqXOw1Ig+Cx4j7ORs/g6MFuEOSlNyXbsJ7gTDmiUuu+HnCcz2Moye45g8SOM5gOlDUOy8j+IALgFWdeeoIZLaAXr+U+trbvPLwRiOzryXYIAzIX5rjWz4Hm5eK1KmaCZX60hJm0z2RQ4q8PRJJLFkOY11xAldlS5tuVZBzPkBA6QJsW6UgON+5YjHjqPx0PSOTrvwY8PHvqrHbC4JvlKq1X42Ca/IN/Ac79G7GrWyAv9RKT68yQQKNa8p0ivb83EgmPAMXKzYRNUmbXyy+Ee/xUVUTs/Mm6tC+VkgFa4Df12JGh/9c7HAYac4zBqoJYABcQLmp43CbxHD1G9j2UnU60IWB5/aefMUeKS2HMbvZXazWp6wMQ0YKWawxc=
